# Generated by Django 2.2.5 on 2019-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabzimal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_picture',
            field=models.ImageField(db_column='category_pitcure', upload_to=''),
        ),
    ]
