# Generated by Django 2.2.5 on 2019-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabzimal', '0002_auto_20190911_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='PaymentsModels',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category_type_id',
            new_name='category_type',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_picture',
            field=models.ImageField(db_column='category_pitcure', upload_to='static//images/'),
        ),
    ]
